### PR TITLE
Updated Resources, FAQ, Terms, Privacy

### PR DESCRIPTION
**Pull request by localastronaut**
Brought back the campaign status banners, updated registration page, changed artist application to registration. Created investor resources section

### CODE REVIEW

**Comment by RevolutionTech** [comment]
Hey @localastronaut sorry it's been taking me a while to get to this.

It's kind of hard to review a PR like this all at once that's doing so many different things together. Ideally, this PR should have been split up into multiple PRs for each feature set you're working on (changes to FAQ, changes to artist form, changes to registration form, etc.).

If it's easy enough for you, do you think you could split up this PR into multiple ones? If you're able to do that, it might be easier for me to find time to review individual ones and make more progress sooner, but if not -- no worries, I will still try to review all of this as soon as I get a chance. Either way though, I'd definitely appreciate it if you consider this when you're working on different features.

**Comment by localastronaut** [comment]
No worries at all. And yeah, absolutely. Is there a way to undo the PR or the commits? Also, do I need to create a new branch for each PR? 

Apologies for loading this one up with a bunch of stuff. I'm still a github amateur ha

**Comment by RevolutionTech** [comment]
No it's okay, I understand.

No need to undo anything, but if you're up to it you could create new branches off of `master` and cherry-pick the relevant commits from the `resources-faq-terms` branch. Unfortunately I don't know how to do that on Github Desktop -- from some quick reading I don't think you can, so you'd have to use the command-line `git`.

That might be a bit challenging though. Alternatively you could tell me which commits _should_ belong together and then I can try to review them independently within this PR knowing how they should be grouped together.

**Comment by localastronaut** [comment]
Alright, I grouped them together based on the page and sorted them by relevance. Let me know if you want the links or id included in this list or just the commit name. Going forward I'll be sure to group and organize them a lot better

**Artist Application**
- Update Artist application copy
- Add campaign date and length to artist sign up form
- Add payback commitment to artist sign up 
- Fix typo on form
- Fix form type, field requirement
- Update application success page

**Home**
- Change "apply" to "sign up" for artists 
- Update base links 

**Artist / Investor Resources**
- Create investor resources template
- Update artist and investor resources with images 

**FAQ**
- Update FAQ
- FAQ updates

**Artists** 
- Bring back campaign status banner

**Registration Page**
- Update registration page
- Update exclusive label

**Terms of Use / Privacy**
- Updated Terms of Use
- Update privacy policy

**Leaderboard**
- Add break to leaderboard title

**Comment by RevolutionTech** [comment]
> Alright, I grouped them together based on the page and sorted them by relevance. Let me know if you want the links or id included in this list or just the commit name. Going forward I'll be sure to group and organize them a lot better
> 
> **Artist Application**
> 
> * Update Artist application copy
> * Add campaign date and length to artist sign up form
> * Add payback commitment to artist sign up
> * Fix typo on form
> * Fix form type, field requirement
> * Update application success page
> 
> **Home**
> 
> * Change "apply" to "sign up" for artists
> * Update base links
> 
> **Artist / Investor Resources**
> 
> * Create investor resources template
> * Update artist and investor resources with images
> 
> **FAQ**
> 
> * Update FAQ
> * FAQ updates
> 
> **Artists**
> 
> * Bring back campaign status banner
> 
> **Registration Page**
> 
> * Update registration page
> * Update exclusive label
> 
> **Terms of Use / Privacy**
> 
> * Updated Terms of Use
> * Update privacy policy
> 
> **Leaderboard**
> 
> * Add break to leaderboard title

Awesome, thanks Brandon. I'm going to try and write a bunch of pull requests with all of these changes.

**Comment by RevolutionTech** [comment]
Thanks for that list, @localastronaut!

I cherry-picked the commits based on that list and ended up with the following pull requests:
https://github.com/RevolutionTech/perdiem-django/pull/363
https://github.com/RevolutionTech/perdiem-django/pull/364
https://github.com/RevolutionTech/perdiem-django/pull/365
https://github.com/RevolutionTech/perdiem-django/pull/366
https://github.com/RevolutionTech/perdiem-django/pull/367
https://github.com/RevolutionTech/perdiem-django/pull/368
https://github.com/RevolutionTech/perdiem-django/pull/369
https://github.com/RevolutionTech/perdiem-django/pull/370

Would you be able to review those PRs above and just validate that they look the way you would expect? I'll start reviewing the ones above as soon as I can.

**Comment by localastronaut** [comment]
Looks good to me! I Checked all of the PR listed and also checked the branches on my github desktop. They were all there.

Not sure why the Travis CI "2 failed checks" are happening. Is that something I need to fix on my end?

**Comment by RevolutionTech** [comment]
> Looks good to me! I Checked all of the PR listed and also checked the branches on my github desktop. They were all there.

Great! I will close out this PR then and start reviewing the individual ones.

> Not sure why the Travis CI "2 failed checks" are happening. Is that something I need to fix on my end?

Some of the changes might be broken or may have broken tests, so yes probably. I'll provide a bit more guidance once I take a look at those PRs.

**Pull request closed without merging**
