### PR TITLE
Leaderboard updates

### PR DESCRIPTION
**Pull request by localastronaut**
Added loader to leaderboard page

### CODE REVIEW

**Comment by RevolutionTech** [comment]
Hey @localastronaut, would you mind merging master into this branch? I just finished rehauling all of the tests so it would be nice to see all of the checks pass on this branch with the new changes. Thanks!

**Comment by localastronaut** [comment]
Yep. Just updated both branches from master

**Comment by RevolutionTech** [comment]
Did you push? I'm not seeing any updates.

**Comment by localastronaut** [comment]
Ahh.. sorry about that. I updated them but they didn't get pushed through. Should be pushed now

**Comment by RevolutionTech** [comment]
This PR looks the same as the other one, so I'll close this one out.

**Pull request closed without merging**
