### PR TITLE
Chart page updates

### PR DESCRIPTION
**Pull request by localastronaut**
- Changed formatting on list name and amount
- Added totals for investments
- Added totals for revenue generated

### CODE REVIEW

**Comment by RevolutionTech** [comment]
Cool, this looks good! I'll add a few commits on this branch so that the numbers you've put in `leaderboard.html` aren't hardcoded.

**Comment by localastronaut** [comment]
Awesome. Do you like "Stats" as the name of the header?

**Comment by RevolutionTech** [comment]
Yeah, I think that's a good name.

**Comment by localastronaut** [comment]
Cool

**Pull request merged**
