### PR TITLE
Added "Funded" overlay to artists list page

### PR DESCRIPTION
**Pull request by localastronaut**
Needs some additional formatting. The way foundation scales it’s
columns makes it difficult to apply a consistent formatting to it.

Also, needs an {% if %} for funded artists

### CODE REVIEW

**Comment by RevolutionTech** [comment]
I added a commit to show the banner only for artists that were recently funded. Two thoughts:
1) Maybe we should only show these banners when "All" artists are selected. When "Funded" is selected, it's kind of redundant. When "Active" is selected, none of these will ever show.
2) What should we show for artists that are not currently raising funds (and never have), or artists that failed to raise money? Maybe nothing, but instead maybe we should have a banner for the artists currently raising money. Thoughts?

**Comment by localastronaut** [comment]
Awesome! I think it would probably make sense to just have the funded campaigns say "funded" and the active ones to be stay the same.

**Comment by RevolutionTech** [comment]
Okay, if we do that users won't be able to tell the difference between active campaigns and failed campaigns from the past. This doesn't really solve the problem of users misclicking into pages that aren't engaging.

**Comment by localastronaut** [comment]
Ahh. I see where you are talking about now. Hmm... Do you think it would make sense to have both active and funded or just active?

**Comment by RevolutionTech** [comment]
I think having active and funded would make sense. For the active campaigns we could even do something like "X% Funded!"

**Comment by localastronaut** [comment]
Yeah, I like that idea a lot. Maybe the active campaigns could have a blue background.

**Comment by RevolutionTech** [comment]
SGTM

**Pull request merged**
